### ISSUE TITLE
HW05: Исключение на некорректной программе

### ISSUE THREAD

**Issue by kajigor** [e2e4b6b7/Simple-prolog-parser#5]
[e06.txt](https://github.com/e2e4b6b7/Simple-prolog-parser/files/5364649/e06.txt)
```
Traceback (most recent call last):
  File "./main.py", line 26, in <module>
    out_parse_result(parse(file.read()))
  File "/home/ev/teach/2020/win/students/RomanVenediktov/hw05/parser.py", line 154, in parse
    parser.parse(text)
  File "/home/ev/.local/lib/python3.6/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/ev/.local/lib/python3.6/site-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/home/ev/.local/lib/python3.6/site-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/home/ev/teach/2020/win/students/RomanVenediktov/hw05/lexer.py", line 36, in t_error
    raise LexerError(t.value[0], t.lexer.lineno, t.lexer.lexpos)
lexer.LexerError: ('1', 1, 0)

```

**Comment by e2e4b6b7** [comment]
Fixed
